# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-15 13:55
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=32)),
                ('calories', models.PositiveIntegerField()),
                ('fats', models.PositiveIntegerField()),
                ('protein', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FoodOfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_price', models.PositiveIntegerField()),
                ('actual_price', models.PositiveIntegerField()),
                ('last_price', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=64)),
                ('available_time', models.PositiveIntegerField()),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contains', to='food.Food')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=512)),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Subscribed',
            fields=[
                ('subscribed_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=16)),
                ('last_name', models.CharField(max_length=16)),
                ('age', models.PositiveIntegerField()),
                ('address', models.CharField(max_length=64)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('postal_code', models.PositiveIntegerField()),
                ('subscription_date', models.DateField(default=datetime.date.today)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='send_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_by', to='food.Subscribed'),
        ),
        migrations.AddField(
            model_name='message',
            name='send_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_to', to='food.Subscribed'),
        ),
        migrations.AddField(
            model_name='foodofer',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to='food.Subscribed'),
        ),
        migrations.AddField(
            model_name='foodofer',
            name='purchaser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bidded_by', to='food.Subscribed'),
        ),
        migrations.AddField(
            model_name='bid',
            name='bidder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='made_by', to='food.Subscribed'),
        ),
        migrations.AddField(
            model_name='bid',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='done_on', to='food.FoodOfer'),
        ),
    ]
